name: eddieantonio
markdown: kramdown

safe: true

# Some metadata... like my social media handles, etc.
me:
  github: https://github.com/eddieantonio
  website: eddieantonio.ca
  resume: /resume/
  cv: /cv/
  twitter: https://twitter.com/_eddieantonio
  bluesky: https://bsky.app/profile/eddieantonio.ca
  blog: https://eddieantonio.ca/blog/

sass:
  style: compressed

plugins:
   - jekyll-redirect-from

whitelist:
    - jekyll-redirect-from

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .ruby-version

