name: eddieantonio
remote_theme: 'LeNPaul/academic'
# Academic theme uses following two attributes
title: Eddie Antonio Santos
description: Assistant Lecturer, Department of Computing Science, University of Alberta

# Some metadata... like my social media handles, etc.
me:
  website: eddieantonio.ca
  resume: /resume/
  cv: /cv/
  github: https://github.com/eddieantonio
  twitter: https://twitter.com/_eddieantonio
  bluesky: https://bsky.app/profile/eddieantonio.ca
  blog: https://eddieantonio.ca/blog/
  orcid: https://orcid.org/0000-0001-5337-715X

safe: true

markdown: kramdown

sass:
  style: compressed

plugins:
  - jekyll-remote-theme
  - jekyll-redirect-from

whitelist:
  - jekyll-remote-theme
  - jekyll-redirect-from

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .ruby-version
