name: eddieantonio
markdown: kramdown

baseurl: http://www.eddieantonio.ca

# Some metadata... like my social media handles, etc.
me:
  github: https://github.com/eddieantonio
  resume: /resume
  twitter: https://twitter.com/_eddieantonio
  blog: http://www.eddieantonio.ca/blog/
